[package]
name = "fere-resources"
version = "0.0.0"
authors = ["Junha Yang <junhayang1@gmail.com>"]
edition = '2018'

[dependencies]
fere-common = { path = "../common" }
gl = "0.14.0"
image = "0.23"
serde = "1.0"