---
dr_2_irradiance:
- deferred/vdr1.glsl
- deferred/fdr2_irradiance.glsl
sh_visualize_single:
- primitive/vsimple.glsl
- effects/GI/fsh_visualize_single.glsl
dr_2:
- deferred/vdr1.glsl
- deferred/fdr2.glsl
basic:
- primitive/vbasic.glsl
- primitive/fbasic.glsl
debug_iden:
- debug/vdebug_basic.glsl
- debug/fdebug_iden.glsl
standard_probe:
- standard/vstandard.glsl
- standard/fstandard_probe.glsl
dr_2_omni:
- deferred/vdr1.glsl
- deferred/fdr2_omni.glsl
probe:
- probe/vprobe.glsl
- probe/fprobe.glsl
geo_visualize:
- effects/geo/vgeo.glsl
- effects/geo/fgeo.glsl
image:
- primitive/vimage.glsl
- primitive/fimage.glsl
debug_3vec:
- primitive/vimage.glsl
- debug/fdebug_3vec.glsl
dr_2_ambient:
- deferred/vdr1.glsl
- deferred/fdr2_ambient.glsl
debug_depth:
- debug/vdebug_basic.glsl
- debug/fdebug_depth.glsl
dr_1:
- deferred/vdr1.glsl
- deferred/fdr1.glsl
dr_3:
- deferred/vdr1.glsl
- deferred/fdr3.glsl
standard:
- standard/vstandard.glsl
- standard/fstandard_tex.glsl
shadow_1:
- shadow/vdepth_only.glsl
- shadow/fdepth_only.glsl
sh_visualize:
- primitive/vsimple.glsl
- effects/GI/fsh_visualize.glsl
debug_test:
- debug/vdebug_basic.glsl
- debug/ftest.glsl
